yfinance_symbols:
  CIBR: "CIBR"
  URA: "URA"
  PLTR: "PLTR"
  MSFT: "MSFT"
  SMH: "SMH"
  ALL_COUNTRY_FUND: "VT"
  RAKUTEN_ALL_COUNTRY_1: "VT"
  RAKUTEN_ALL_COUNTRY_2: "VT"
  EMAXIS_ALL_COUNTRY: "VT"
  EMAXIS_ALL_COUNTRY_TAXABLE: "ACWI"
  SP500_FUND: "VOO"
  RAKUTEN_SP500: "VOO"
  EMAXIS_SP500_1: "VOO"
  EMAXIS_SP500_2: "VOO"
  EMAXIS_SP500_3: "VOO"
  TOYOTA_US_PROXY: "TM"
  VT: "VT"
  VOO: "VOO"
  SOXX: "SOXX"
  USDJPY: "USDJPY=X"
